### ISSUE TITLE
Allow virtualbox tasks to be pairs (task-fn, error-handle-fn)

### ISSUE THREAD

**Issue by tbatchelli** [tbatchelli/vmfest#1]
Make it so that when executing a vbox-task, the error-handler-fn is used if supplied, and that a sane error handler is used as a default.

**Comment by hugoduncan** [comment]
Should the agent be restarted by default?

**Comment by tbatchelli** [comment]
I'd like to have the caller make that decision, but I haven't really made up my mind on this one.
