### ISSUE TITLE
Minor corrections for Readme.md

### ISSUE THREAD

**Issue by mchampine** [tbatchelli/vmfest#13]
In the section "Now let's say you want to start 10 instances of the same model."

You have:

;; create the instances
(def my-machines (map #(instance my-server % :ubuntu-10-10-64bit :micro)))

It should be:

;; create the instances
(def my-machines (map #(instance my-server % :ubuntu-10-10-64bit :micro) clone-names))

Also, there are just 6 instances defined in clone-names, not 10.

**Comment by tbatchelli** [comment]
I ended up rewriting the whole README. Now the code is in https://github.com/pallet/vmfest-playground so it can be easily tested.
