### ISSUE TITLE
Enable zero-config use of vmfest

### ISSUE THREAD

**Issue by hugoduncan** [tbatchelli/vmfest#37]
Using vmfest currently requires external starting of vboxwebsrv.

It would be nice to have vboxwebsrv be started automatically, or for vmfest to use the non-http virtualbox api.

**Comment by tbatchelli** [comment]
Fixed by e377485f0464b91a8e788a58fc52566049b3377e : support XPCOm (not-http vbox api, requires no vboxwebsrvr running)
