### ISSUE TITLE
Provisioned VMs lose state on shutdown

### ISSUE THREAD

**Issue by davidsantiago** [tbatchelli/vmfest#5]
As we discussed just now on IRC, when you shutdown a VM created with vmfest, it loses all its state and reverts back to the raw image, losing all login data and other state. You mentioned that you might have a workaround for this and asked me to file this bug.

**Comment by tbatchelli** [comment]
fixed by ce8d6c24ecd36b783c8635c19c9d7f94dd557c75 . Now all image models are installed as multi-attach, as opposed to immutable.
