### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by jcrosby** [tbatchelli/vmfest#52]
When running the first lines of the tutorial in the lein repl, I receive the following error:

user=> (use 'vmfest.manager)
ClassNotFoundException org.virtualbox_4_2.IVirtualBox  java.net.URLClassLoader$1.run (URLClassLoader.java:202)

Here is my project.clj:

(defproject my-app "0.1.0-SNAPSHOT"
  :description "My App"
  :dependencies [[org.clojure/clojure "1.4.0"]
                 [com.palletops/pallet "0.8.0-beta.1"]
                 [vmfest "0.3.0-alpha.2"]
                 [org.clojars.tbatchelli/vboxjxpcom "4.2.4"]]
  :jvm-opts ["-Dvbox.home=/Applications/VirtualBox.app/Contents/MacOS"]
  :repositories {"sonatype-snapshots" "https://oss.sonatype.org/content/repositories/snapshots"
                 "sonatype" "https://oss.sonatype.org/content/repositories/releases/"})

Here is my ~/.lein/profiles.clj:

{:user {:plugins [[com.palletops/pallet-lein "0.6.0-beta.3"]]}}

**Comment by tbatchelli** [comment]
Jon,

This is a known bug in pallet-lein 0.6.0-beta.3, fixed in -beta.4. Try again and this error should go away.

Also, notice that I fixed the README of pallet-vmfest 0.3.0 today, specifically this: 

```
(def vmfest (compute-service "vmfest" nil nil))
```

Toni.

**Comment by jcrosby** [comment]
Thank you. This resolved the issue and the tutorial is working properly now.

**Comment by skelter** [comment]
What actually causes this?  I have an old project I'm trying to resurrect.  I'm getting this at the repl when I 
(require 'vmfest.manager)

**Comment by tbatchelli** [comment]
This was a bug in pallet-lein that removed the virtualbox library from the classpath. This should not happen anymore with the latest versions of pallet-lein. If you are not using pallet-lein or you are using pallet-lein 0.6.0-beta.4 or newer and it still happen then it is a different issue and you should open a new issue with the full stack trace and versions you are using, along with how to trigger the exception.
